### PR TITLE
Starting to create more tests

### PR DESCRIPTION
**Pull request by Jean-Baptiste-Camps**

### CODE REVIEW

**Comment by florian-gandon** [comment]
I see you are doing some testing lately.
There is an usual way to format it which is given-when-then: https://martinfowler.com/bliki/GivenWhenThen.html
(my 2 cents)
Florian

**Comment by Jean-Baptiste-Camps** [comment]
Hi @florian-gandon ! Thanks for the input !
As I understand it, it is a way to document the contents of the test. For instance, if I take one of my existing tests,

```python
# FEATURE: text normalisation before further processing
def test_normalise(self):
    # SCENARIO: I want to normalise a string of text with defaults settings
    # GIVEN the following string
    text = " Hello,  Mr. 𓀁, how are §§ you; doing?"
    # WHEN I apply normalisation
    result = superstyl.preproc.tuyau.normalise(text)
    # THEN I expect the following output in lower case and without punctuation and symbols
    expected_default = "hello mr how are you doing"
    self.assertEqual(result, expected_default)
```
Or do I miss something ?

**Comment by florian-gandon** [comment]
Yes, for instance.
You could also put it in the method name so when failing (or succeed) it is easier to read in the console or in the IDE. Like that:
```
def givenTextWithUpperCasePunctuationAndSymbols_whenNormalizing_thenTextIsLowerCaseWithoutPunctuation(self):
    # GIVEN
    text = " Hello,  Mr. 𓀁, how are §§ you; doing?"
    # WHEN
    result = superstyl.preproc.tuyau.normalise(text)
    # THEN
    expected_default = "hello mr how are you doing"
    self.assertEqual(result, expected_default)
```
(or optionally without comments as there is only one line for each part)
 The method could written in a file or a class which describes the feature. I'm not sure what is the usual manner in Python.

**Comment by Jean-Baptiste-Camps** [comment]
Nice ! I'm not using a lot of class oriented stuff right now, but for the tests, I'm using a class by feature of the main entry points (so a class for data loading, a class for training, etc.), in which I have a test function definition for each function of the source library.

**Comment by Jean-Baptiste-Camps** [comment]
Merging and closing this one as I need to implement and test a completely new function, but please give feedback whenever you want, it is much appreciated :)

**Pull request merged**
